---
uuid: "2a0ec304-c388-4bbd-87de-d0022f20568b"
title: "Particle Ninja"
author: null
description: "Découpez les particles mais gare aux bombes !"
avatar: "asterisk"
contents: "<xml xmlns=\"http://www.w3.org/1999/xhtml\"><variables><variable type=\"\
  \" id=\"M({$bFP8@EawrJ(Yr/::\">particule</variable><variable type=\"\" id=\"I#03~lm~:s;%.XZs(qM$\"\
  >vitesseY</variable><variable type=\"\" id=\"G+^DqRE-H!8hZN8$o``7\">GRAVITE</variable><variable\
  \ type=\"\" id=\"@!pQSm0XZ{bgAAfgO=LQ\">particuleY</variable><variable type=\"\"\
  \ id=\"DFS,riwFR6C!zE~%7:]o\">particuleX</variable><variable type=\"\" id=\"_eYiame[X:ES)ESE,5|8\"\
  >deltaY</variable><variable type=\"\" id=\"jI[dJMth[=vO{$!K[TrB\">item</variable><variable\
  \ type=\"\" id=\"qU7^X3M5hYY9.6q+bgGI\">vitesseX</variable><variable type=\"\" id=\"\
  v6-q$!T2B#P1m;auQgYj\">rotationParticule</variable></variables><block type=\"screen_size\"\
  \ id=\"v032,bS4},tm,Hu/,2Zl\" x=\"65\" y=\"5\"><field name=\"W\">800</field><field\
  \ name=\"H\">420</field><next><block type=\"actor\" id=\"m4YGR8e*dWR5e[lI0cyI\"\
  ><field name=\"NAME\" id=\"M({$bFP8@EawrJ(Yr/::\" variabletype=\"\">particule</field><field\
  \ name=\"ANCHOR\">('center','middle')</field><field name=\"POSX\">40</field><field\
  \ name=\"POSY\">420</field><next><block type=\"variables_set\" id=\"vCkB*YpuMJ]ndlZ8eZd`\"\
  ><field name=\"VAR\" id=\"G+^DqRE-H!8hZN8$o``7\" variabletype=\"\">GRAVITE</field><value\
  \ name=\"VALUE\"><block type=\"math_number\" id=\"=oe+)o[jt*ckwmz4)*ss\"><field\
  \ name=\"NUM\">0.35</field></block></value><next><block type=\"procedures_callnoreturn\"\
  \ id=\"h`WH#/x$x#W-6-X3M}*r\"><mutation name=\"preparer la trajectoire\"></mutation></block></next></block></next></block></next></block><block\
  \ type=\"procedures_defnoreturn\" id=\"kBQj/[pXq5td#7%oY;g[\" x=\"484\" y=\"132\"\
  ><field name=\"NAME\">preparer la trajectoire</field><comment pinned=\"false\" h=\"\
  80\" w=\"160\">Describe this function...</comment><statement name=\"STACK\"><block\
  \ type=\"variables_set\" id=\"ruB9qGaIwOU~a.?BVWN[\"><field name=\"VAR\" id=\"DFS,riwFR6C!zE~%7:]o\"\
  \ variabletype=\"\">particuleX</field><value name=\"VALUE\"><block type=\"math_random_int\"\
  \ id=\"wJ]G%O3xn:chZYm+sL5L\"><value name=\"FROM\"><shadow type=\"math_number\"\
  \ id=\"/lvjRTr$|=]%=u7}m]Zz\"><field name=\"NUM\">20</field></shadow></value><value\
  \ name=\"TO\"><shadow type=\"math_number\" id=\".F@u_WRGlk/.-PfZ(21-\"><field name=\"\
  NUM\">300</field></shadow></value></block></value><next><block type=\"variables_set\"\
  \ id=\")5Lo+SZ8|ps02@HoxLyE\"><field name=\"VAR\" id=\"@!pQSm0XZ{bgAAfgO=LQ\" variabletype=\"\
  \">particuleY</field><value name=\"VALUE\"><block type=\"math_number\" id=\"y$1wx$eks;]cxg9Jx^~5\"\
  ><field name=\"NUM\">420</field></block></value><next><block type=\"variables_set\"\
  \ id=\"I93rI.c^R[,Ymiwg!*sY\"><field name=\"VAR\" id=\"qU7^X3M5hYY9.6q+bgGI\" variabletype=\"\
  \">vitesseX</field><value name=\"VALUE\"><block type=\"math_random_int\" id=\"AY?KCh9uBzWm8K6UbyE@\"\
  ><value name=\"FROM\"><shadow type=\"math_number\" id=\"F4gI+VKf)k7rZcL*%xQY\"><field\
  \ name=\"NUM\">-1</field></shadow></value><value name=\"TO\"><shadow type=\"math_number\"\
  \ id=\".XzW}l}DWD)bV#hjG+hp\"><field name=\"NUM\">8</field></shadow></value></block></value><next><block\
  \ type=\"variables_set\" id=\"chi%6:_aIodF@Pc!LdZ8\"><field name=\"VAR\" id=\"I#03~lm~:s;%.XZs(qM$\"\
  \ variabletype=\"\">vitesseY</field><value name=\"VALUE\"><block type=\"math_random_int\"\
  \ id=\"ks2dn.`sTXV]^]x.wdEK\"><value name=\"FROM\"><shadow type=\"math_number\"\
  \ id=\";HG!JdrGs(V6S{d.,=(v\"><field name=\"NUM\">-18</field></shadow></value><value\
  \ name=\"TO\"><shadow type=\"math_number\" id=\"C~HcbnNLC^[bI!gZ[$uf\"><field name=\"\
  NUM\">-12</field></shadow></value></block></value><next><block type=\"variables_set\"\
  \ id=\"N`L+]Vz$+H!zQ]~nau.9\"><field name=\"VAR\" id=\"v6-q$!T2B#P1m;auQgYj\" variabletype=\"\
  \">rotationParticule</field><value name=\"VALUE\"><block type=\"math_number\" id=\"\
  %_S-J/6_-.[EFQSW7r@1\"><field name=\"NUM\">0</field></block></value></block></next></block></next></block></next></block></next></block></statement></block><block\
  \ type=\"draw_loop\" id=\"[B4$_D]M_v+G2@MOL!#c\" x=\"66\" y=\"228\"><statement name=\"\
  STATEMENTS\"><block type=\"screen_blit\" id=\"9uz{lJA=PdjMJy(ggrk9\"><value name=\"\
  IMAGE\"><shadow type=\"text\" id=\"_E|90G`|~U,FCD:;d7R?\"><field name=\"TEXT\">cosmos</field></shadow></value><value\
  \ name=\"TOP\"><shadow type=\"math_number\" id=\".^C7T[Z7JElX0|0KCvAS\"><field name=\"\
  NUM\">0</field></shadow></value><value name=\"LEFT\"><shadow type=\"math_number\"\
  \ id=\"2C@Hd::{Sk(|7`Z3#K0v\"><field name=\"NUM\">0</field></shadow></value><next><block\
  \ type=\"actor_draw\" id=\"?s-7gNgASIY?g~8Y2WCX\"><field name=\"ACTOR\" id=\"M({$bFP8@EawrJ(Yr/::\"\
  \ variabletype=\"\">particule</field></block></next></block></statement></block><block\
  \ type=\"update_loop\" id=\":qi~DpKG`N;-@{cf=?*o\" x=\"70\" y=\"333\"><statement\
  \ name=\"STATEMENTS\"><block type=\"procedures_callnoreturn\" id=\"WLwzB85gqgRh7~$n?*fm\"\
  ><mutation name=\"deplacer la particule\"></mutation><next><block type=\"controls_if\"\
  \ id=\"R1OXTY)zYj2klh1xX%TK\"><value name=\"IF0\"><block type=\"logic_compare\"\
  \ id=\"V[8kUp{Avt]/@Eigv2w,\"><field name=\"OP\">GT</field><value name=\"A\"><block\
  \ type=\"get_actor_property\" id=\"=LpW4rJognF07q~.o5{L\"><field name=\"PROPERTY\"\
  >y</field><field name=\"ACTOR\" id=\"M({$bFP8@EawrJ(Yr/::\" variabletype=\"\">particule</field></block></value><value\
  \ name=\"B\"><block type=\"math_number\" id=\"_$~GoK=xl$MH}:e{Ahx8\"><field name=\"\
  NUM\">500</field></block></value></block></value><statement name=\"DO0\"><block\
  \ type=\"procedures_callnoreturn\" id=\"jIbDk!9:i}qJxva?3)]y\"><mutation name=\"\
  preparer la trajectoire\"></mutation></block></statement></block></next></block></statement></block><block\
  \ type=\"procedures_defnoreturn\" id=\"fQkJ;jH4~1~q}spYN7V,\" x=\"474\" y=\"463\"\
  ><field name=\"NAME\">deplacer la particule</field><comment pinned=\"false\" h=\"\
  80\" w=\"160\">Describe this function...</comment><statement name=\"STACK\"><block\
  \ type=\"variables_set\" id=\"pB2_L-hMlsOBzBg2;!0i\"><field name=\"VAR\" id=\"_eYiame[X:ES)ESE,5|8\"\
  \ variabletype=\"\">deltaY</field><value name=\"VALUE\"><block type=\"variables_get\"\
  \ id=\"xF!WOdsO*XMF(+b7`2i0\"><field name=\"VAR\" id=\"I#03~lm~:s;%.XZs(qM$\" variabletype=\"\
  \">vitesseY</field></block></value><next><block type=\"math_change\" id=\":GD,Lwehm_?pL?k6wRr[\"\
  ><field name=\"VAR\" id=\"I#03~lm~:s;%.XZs(qM$\" variabletype=\"\">vitesseY</field><value\
  \ name=\"DELTA\"><shadow type=\"math_number\" id=\"akqkYOYapi7dUO$Hi;in\"><field\
  \ name=\"NUM\">1</field></shadow><block type=\"variables_get\" id=\"s]F@z!nmYk}LGlPKVj*S\"\
  ><field name=\"VAR\" id=\"G+^DqRE-H!8hZN8$o``7\" variabletype=\"\">GRAVITE</field></block></value><next><block\
  \ type=\"math_change\" id=\"VLaGm1*6.b~^R`8c?a%D\"><field name=\"VAR\" id=\"DFS,riwFR6C!zE~%7:]o\"\
  \ variabletype=\"\">particuleX</field><value name=\"DELTA\"><shadow type=\"math_number\"\
  \ id=\"64VO#$F%_KPum~[_N:c8\"><field name=\"NUM\">3</field></shadow><block type=\"\
  variables_get\" id=\"u]hl|G~*cG=v9/:09?jm\"><field name=\"VAR\" id=\"qU7^X3M5hYY9.6q+bgGI\"\
  \ variabletype=\"\">vitesseX</field></block></value><next><block type=\"math_change\"\
  \ id=\"D9x2Z!#twoR^Ow^CV$nw\"><field name=\"VAR\" id=\"@!pQSm0XZ{bgAAfgO=LQ\" variabletype=\"\
  \">particuleY</field><value name=\"DELTA\"><shadow type=\"math_number\" id=\"+:jViU9?PkV5x7PU#t0u\"\
  ><field name=\"NUM\">1</field></shadow><block type=\"math_arithmetic\" id=\"F.mWeSy2pqVcZDM{41#*\"\
  ><field name=\"OP\">DIVIDE</field><value name=\"A\"><shadow type=\"math_number\"\
  \ id=\"ED[k[2]T=DAb:(5uCv#|\"><field name=\"NUM\">1</field></shadow><block type=\"\
  math_arithmetic\" id=\"/)x|OA@NK$K#Vu/E]P%]\" inline=\"false\"><field name=\"OP\"\
  >ADD</field><value name=\"A\"><shadow type=\"math_number\" id=\"ga=F9$s2|FJLv(LjiF7Q\"\
  ><field name=\"NUM\">1</field></shadow><block type=\"variables_get\" id=\"?SujOv~ZU2*_L+a.PX,Y\"\
  ><field name=\"VAR\" id=\"I#03~lm~:s;%.XZs(qM$\" variabletype=\"\">vitesseY</field></block></value><value\
  \ name=\"B\"><shadow type=\"math_number\" id=\"USOh$].(nQQt%6zAzMj%\"><field name=\"\
  NUM\">1</field></shadow><block type=\"variables_get\" id=\"qWg(b?`3(l|UUqvPoM^~\"\
  ><field name=\"VAR\" id=\"_eYiame[X:ES)ESE,5|8\" variabletype=\"\">deltaY</field></block></value></block></value><value\
  \ name=\"B\"><shadow type=\"math_number\" id=\":52SrjC/7jsC8*7AyDyp\"><field name=\"\
  NUM\">2</field></shadow></value></block></value><next><block type=\"actor_position\"\
  \ id=\"-H+=Q;We;0`Q$_y5VL=?\"><field name=\"ACTOR\" id=\"M({$bFP8@EawrJ(Yr/::\"\
  \ variabletype=\"\">particule</field><value name=\"POSX\"><shadow type=\"math_number\"\
  \ id=\"q8,HFfbmlR,A^Vn}kuh]\"><field name=\"NUM\">0</field></shadow><block type=\"\
  variables_get\" id=\"]1!;mK(,Gn7z]Eei)]Xo\"><field name=\"VAR\" id=\"DFS,riwFR6C!zE~%7:]o\"\
  \ variabletype=\"\">particuleX</field></block></value><value name=\"POSY\"><shadow\
  \ type=\"math_number\" id=\"/aMHkr1i]-aA(,:O^N4z\"><field name=\"NUM\">0</field></shadow><block\
  \ type=\"variables_get\" id=\"+5=H+9y%PSI?xDhk-qMK\"><field name=\"VAR\" id=\"@!pQSm0XZ{bgAAfgO=LQ\"\
  \ variabletype=\"\">particuleY</field></block></value></block></next></block></next></block></next></block></next></block></statement></block><block\
  \ type=\"clock_schedule_interval\" id=\"0.;O6@3jW1*m8+kw{^.!\" x=\"346\" y=\"709\"\
  ><value name=\"INTERVAL\"><shadow type=\"math_number\" id=\"N$^v`(3Kr(O?HJ%!Yy/m\"\
  ><field name=\"NUM\">0.05</field></shadow></value><statement name=\"STATEMENTS\"\
  ><block type=\"math_change\" id=\"sI6@WnYIiLTKL%eAR%dl\"><field name=\"VAR\" id=\"\
  v6-q$!T2B#P1m;auQgYj\" variabletype=\"\">rotationParticule</field><value name=\"\
  DELTA\"><shadow type=\"math_number\" id=\"Amh$nqTzLBZtS*rzH0^x\"><field name=\"\
  NUM\">1</field></shadow></value><next><block type=\"actor_image\" id=\"nx5o3,?dfZ,KTlA.r,??\"\
  ><field name=\"ACTOR\" id=\"M({$bFP8@EawrJ(Yr/::\" variabletype=\"\">particule</field><value\
  \ name=\"IMAGE\"><shadow type=\"text\" id=\"4FE)U@pnWg8AEkJbN]^A\"><field name=\"\
  TEXT\"></field></shadow><block type=\"text_join\" id=\"QU`tjxJ~+1xf@S8QII9=\"><mutation\
  \ items=\"2\"></mutation><value name=\"ADD0\"><block type=\"text\" id=\"G5;FM@~:xAZRmU6B%gu:\"\
  ><field name=\"TEXT\">particule</field></block></value><value name=\"ADD1\"><block\
  \ type=\"math_modulo\" id=\",ETZ}(-`Acv|R;)Rk#o^\"><value name=\"DIVIDEND\"><shadow\
  \ type=\"math_number\" id=\"8EM@kif#6})`TR0mL#^#\"><field name=\"NUM\">64</field></shadow><block\
  \ type=\"variables_get\" id=\"+MaY%!r7=W-e}d:,fMf`\"><field name=\"VAR\" id=\"v6-q$!T2B#P1m;auQgYj\"\
  \ variabletype=\"\">rotationParticule</field></block></value><value name=\"DIVISOR\"\
  ><shadow type=\"math_number\" id=\"s5^0P]D$jB4oQ:#8@S,b\"><field name=\"NUM\">4</field></shadow></value></block></value></block></value></block></next></block></statement></block></xml>"
generatedContents: "import random\nfrom numbers import Number\n\nparticule = None\n\
  vitesseY = None\nGRAVITE = None\nparticuleY = None\nparticuleX = None\ndeltaY =\
  \ None\nitem = None\nvitesseX = None\nrotationParticule = None\n\n\"\"\"Describe\
  \ this function...\n\"\"\"\ndef preparer_la_trajectoire():\n  global particule,\
  \ vitesseY, GRAVITE, particuleY, particuleX, deltaY, item, vitesseX, rotationParticule\n\
  \  particuleX = random.randint(20, 300)\n  particuleY = 420\n  vitesseX = random.randint(-1,\
  \ 8)\n  vitesseY = random.randint(-18, -12)\n  rotationParticule = 0\n\n\"\"\"Describe\
  \ this function...\n\"\"\"\ndef deplacer_la_particule():\n  global particule, vitesseY,\
  \ GRAVITE, particuleY, particuleX, deltaY, item, vitesseX, rotationParticule\n \
  \ deltaY = vitesseY\n  vitesseY = (vitesseY if isinstance(vitesseY, Number) else\
  \ 0) + GRAVITE\n  particuleX = (particuleX if isinstance(particuleX, Number) else\
  \ 0) + vitesseX\n  particuleY = (particuleY if isinstance(particuleY, Number) else\
  \ 0) + (vitesseY + deltaY) / 2\n  particule.pos = particuleX,particuleY\n\ndef scheduled2():\n\
  \  global particule, vitesseY, GRAVITE, particuleY, particuleX, deltaY, item, vitesseX,\
  \ rotationParticule\n  rotationParticule = (rotationParticule if isinstance(rotationParticule,\
  \ Number) else 0) + 1\n  particule.image=(str('particule') + str(rotationParticule\
  \ % 4))\n\n\nWIDTH=800\nHEIGHT=420\nparticule = Actor('particule',anchor=('center','middle'),pos=(40,420))\n\
  GRAVITE = 0.35\npreparer_la_trajectoire()\n\ndef draw():\n  global particule, vitesseY,\
  \ GRAVITE, particuleY, particuleX, deltaY, item, vitesseX, rotationParticule\n \
  \ screen.blit('cosmos',(0,0))\n  particule.draw()\n\n\ndef update():\n  global particule,\
  \ vitesseY, GRAVITE, particuleY, particuleX, deltaY, item, vitesseX, rotationParticule\n\
  \  deplacer_la_particule()\n  if particule.y > 500:\n    preparer_la_trajectoire()\n\
  \n\nclock.schedule_interval(scheduled2,0.05)\n"
type: "PYGAMEZERO"
createdOn: 1510258407601
lastUpdatedOn: 1510262384502
template: true
environment: null
baseImage: null
parameters: null
